-- MySQL Script generated by MySQL Workbench
-- Wed Mar  6 12:01:04 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema mi_base_de_datos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mi_base_de_datos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mi_base_de_datos` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`chat` ;

CREATE TABLE IF NOT EXISTS `mydb`.`chat` (
  `id` INT NOT NULL,
  `mensaje_id` INT NOT NULL,
  `pedido_id` INT NOT NULL,
  PRIMARY KEY (`id`, `mensaje_id`, `pedido_id`),
  INDEX `fk_chat_mensaje1_idx` (`mensaje_id` ASC) VISIBLE,
  INDEX `fk_chat_pedido1_idx` (`pedido_id` ASC) VISIBLE,
  CONSTRAINT `fk_chat_mensaje1`
    FOREIGN KEY (`mensaje_id`)
    REFERENCES `mydb`.`mensaje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chat_pedido1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `mydb`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mensaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`mensaje` ;

CREATE TABLE IF NOT EXISTS `mydb`.`mensaje` (
  `id` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` DATETIME NOT NULL,
  `contenido` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `id` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `efectivo` INT NULL,
  `propina` INT NOT NULL,
  `costo` INT NOT NULL,
  `total` INT NOT NULL,
  `activo` TINYINT NOT NULL,
  `pagado` TINYINT NOT NULL,
  `salio` TINYINT NOT NULL,
  `entregado` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido_tiene_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pedido_tiene_producto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pedido_tiene_producto` (
  `pedido_id` INT NOT NULL,
  `producto_id` INT NOT NULL,
  PRIMARY KEY (`pedido_id`, `producto_id`),
  INDEX `fk_pedido_has_producto_producto1_idx` (`producto_id` ASC) VISIBLE,
  INDEX `fk_pedido_has_producto_pedido1_idx` (`pedido_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_has_producto_pedido1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `mydb`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_has_producto_producto1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `mydb`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`producto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`producto` (
  `id` INT NOT NULL,
  `precio` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `existencia` INT NOT NULL,
  `promocion` TINYINT NOT NULL,
  `imagen` BLOB NOT NULL,
  `categoria` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL,
  `rol` VARCHAR(13) NOT NULL,
  `clave` VARCHAR(10) NOT NULL,
  `nombre_completo` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `preferencias` VARCHAR(500) NOT NULL,
  `ubicacion` VARCHAR(500) NOT NULL,
  `imagen_perfil` BLOB NOT NULL,
  `mensaje_id` INT NOT NULL,
  `pedido_id` INT NOT NULL,
  PRIMARY KEY (`id`, `mensaje_id`, `pedido_id`),
  INDEX `fk_usuario_mensaje_idx` (`mensaje_id` ASC) VISIBLE,
  INDEX `fk_usuario_pedido1_idx` (`pedido_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_mensaje`
    FOREIGN KEY (`mensaje_id`)
    REFERENCES `mydb`.`mensaje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_pedido1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `mydb`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mi_base_de_datos` ;

-- -----------------------------------------------------
-- Table `mi_base_de_datos`.`chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mi_base_de_datos`.`chat` ;

CREATE TABLE IF NOT EXISTS `mi_base_de_datos`.`chat` (
  `id` INT(11) NOT NULL,
  `mensaje_id` INT(11) NOT NULL,
  `pedido_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `mensaje_id`, `pedido_id`),
  INDEX `fk_chat_mensaje1_idx` (`mensaje_id` ASC) VISIBLE,
  INDEX `fk_chat_pedido1_idx` (`pedido_id` ASC) VISIBLE,
  CONSTRAINT `fk_chat_mensaje1`
    FOREIGN KEY (`mensaje_id`)
    REFERENCES `mi_base_de_datos`.`mensaje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chat_pedido1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `mi_base_de_datos`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mi_base_de_datos`.`mensaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mi_base_de_datos`.`mensaje` ;

CREATE TABLE IF NOT EXISTS `mi_base_de_datos`.`mensaje` (
  `id` INT(11) NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` DATETIME NOT NULL,
  `contenido` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mi_base_de_datos`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mi_base_de_datos`.`pedido` ;

CREATE TABLE IF NOT EXISTS `mi_base_de_datos`.`pedido` (
  `id` INT(11) NOT NULL,
  `fecha` DATE NOT NULL,
  `efectivo` INT(11) NULL DEFAULT NULL,
  `propina` INT(11) NOT NULL,
  `costo` INT(11) NOT NULL,
  `total` INT(11) NOT NULL,
  `activo` TINYINT(4) NOT NULL,
  `pagado` TINYINT(4) NOT NULL,
  `salio` TINYINT(4) NOT NULL,
  `entregado` TINYINT(4) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mi_base_de_datos`.`pedido_tiene_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mi_base_de_datos`.`pedido_tiene_producto` ;

CREATE TABLE IF NOT EXISTS `mi_base_de_datos`.`pedido_tiene_producto` (
  `pedido_id` INT(11) NOT NULL,
  `producto_id` INT(11) NOT NULL,
  PRIMARY KEY (`pedido_id`, `producto_id`),
  INDEX `fk_pedido_has_producto_producto1_idx` (`producto_id` ASC) VISIBLE,
  INDEX `fk_pedido_has_producto_pedido1_idx` (`pedido_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_has_producto_pedido1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `mi_base_de_datos`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_has_producto_producto1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `mi_base_de_datos`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mi_base_de_datos`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mi_base_de_datos`.`producto` ;

CREATE TABLE IF NOT EXISTS `mi_base_de_datos`.`producto` (
  `id` INT(11) NOT NULL,
  `precio` INT(11) NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `existencia` INT(11) NOT NULL,
  `promocion` TINYINT(4) NOT NULL,
  `categoria` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mi_base_de_datos`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mi_base_de_datos`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mi_base_de_datos`.`usuario` (
  `id` INT(11) NOT NULL,
  `rol` VARCHAR(13) NOT NULL,
  `clave` VARCHAR(10) NOT NULL,
  `nombre_completo` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `preferencias` VARCHAR(500) NOT NULL,
  `ubicacion` VARCHAR(500) NOT NULL,
  `imagen_perfil` BLOB NOT NULL,
  `mensaje_id` INT(11) NOT NULL,
  `pedido_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `mensaje_id`, `pedido_id`),
  INDEX `fk_usuario_mensaje_idx` (`mensaje_id` ASC) VISIBLE,
  INDEX `fk_usuario_pedido1_idx` (`pedido_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_mensaje`
    FOREIGN KEY (`mensaje_id`)
    REFERENCES `mi_base_de_datos`.`mensaje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_pedido1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `mi_base_de_datos`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
